#!/bin/bash

# i found the below steps from:
# https://developer.mongodb.com/community/forums/t/problems-trying-to-compile-mongocxx/2084
function install_mongocxx_dependencies() {
  TOP_DIR=$(pwd)
  MONGO_C_DRIVER_VERSION=1.25.4
  C_SOURCE=mongo-c-driver
  
  #sudo apt-get install cmake libmongoc-1.0-0 libbson-1.0 cmake libssl-dev libsasl2-dev zlib1g-dev
  
  #wget  "https://github.com/mongodb/mongo-c-driver/archive/refs/tags/$MONGO_C_DRIVER_VERSION.tar.gz" \
  #	--output-document="$C_SOURCE.tar.gz"
  	
  #tar xf "${C_SOURCE}.tar.gz"
  
  git clone https://github.com/mongodb/$C_SOURCE.git \
      --branch r1.25 --depth 1
  
  cd $C_SOURCE
  mkdir cmake-build
  cd cmake-build
  cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
  sudo make install
  
  cd ..
  cd ..
  git clone https://github.com/mongodb/mongo-cxx-driver.git \
      --branch releases/stable --depth 1
  cd mongo-cxx-driver/build

  sudo cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DBSONCXX_POLY_USE_MNMLSTC=1 \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      #-DCMAKE_PREFIX_PATH=~/mongo-c-driver/


  sudo make
  sudo make install
  cd $TOP_DIR
  sudo rm -rf mongo-c-driver-1.25.0*
}

function main() {
  install_mongocxx_dependencies
}

main